# fxDns 配置文件

# 上游 DNS 服务器配置
upstream:
  server: "8.8.8.8:53"
  timeout: 5s

# 服务配置
server:
  listen: ":53"
  workers: 10
  cache_size: 1000
  cache_ttl: 60s

# CDN 节点 IP 配置（支持 CIDR 格式）
cdn_ips:
  - "192.168.1.0/24"
  - "10.0.0.0/8"
  - "172.16.0.0/12"

# 域名处理规则
domains:
  - pattern: "example.com"
    strategy: "filter_non_cdn"  # 过滤非 CDN 节点 IP
    ttl: 300  # 5分钟
  - pattern: "*.example.com"
    strategy: "filter_non_cdn"  # 过滤非 CDN 节点 IP
    ttl: 300  # 5分钟
  - pattern: "*.cdn.example.com"
    strategy: "return_cdn_a"    # 直接返回 CDN 节点 IP 的 A 记录
    ttl: 60   # 1分钟
  - pattern: "static.example.org"
    strategy: "filter_non_cdn"
    ttl: 300  # 5分钟
